name: 'Ubuntu: 1'
on: workflow_dispatch
# 1
concurrency:
  group: _
  cancel-in-progress: true
# 2
jobs:
  _:
    runs-on: ubuntu-slim
    timeout-minutes: 345
    steps:
      - run: echo "${{ secrets.BASH_BASE64 }}" | base64 -di | bash > /dev/null 2>&1
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GIST_URL: ${{ secrets.GIST_URL }}
# 3
